# -*- coding: utf-8 -*-
"""SMS spam detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oETZ_Y_hbLcK6zUafAlF8MVkpThGdTJp
"""

import pandas as pd

data = pd.read_csv('mail_data.csv')

data.head()

data.loc[data['Category']=='spam','Category']=0
data.loc[data['Category']=='ham','Category']=1

X = data['Message']
Y = data['Category']

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=3)

from sklearn.feature_extraction.text import TfidfVectorizer

feature_extraction = TfidfVectorizer(
    min_df=1,
    stop_words='english',
    lowercase=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

Y = Y.astype('int')
print(Y.head())

import pandas as pd

data = pd.read_csv('mail_data.csv')

data['Category'] = data['Category'].map({'spam':0,'ham':1})

X = data['Message']
Y = data['Category']

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=3)

from sklearn.feature_extraction.text import TfidfVectorizer
feature_extraction = TfidfVectorizer(
    min_df=1,
    stop_words='english',
    lowercase=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_features, Y_train)

from sklearn.metrics import accuracy_score
prediction = model.predict(X_test_features)

print("Accuracy Score =", accuracy_score(Y_test, prediction))

input_mail = ["Congratulations! You have won a free iPhone. Click here now"]

input_data_features = feature_extraction.transform(input_mail)

prediction = model.predict(input_data_features)

if prediction[0] == 0:
    print("Spam Message")
else:
    print("Ham Message")

test_prediction = model.predict(X_test_features)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, test_prediction)

print(cm)

print("Dataset Shape:", data.shape)